version: '3.9'

services:
  java_app:
    container_name: java_graphql_app
    image: img_java_graphql_app:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://java_db:3306/graphql_db?serverTimezone=America/Bogota
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - java_db
    restart: on-failure

  java_db:
    image: mysql:latest
    container_name: java_graphql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: graphql_db